import { Inter } from "next/font/google";

import "@/config/firebase";
import { AuthContextProvider } from "@/shared/context/AuthContext";
import { ThreadContextProvider } from "@/shared/context/ThreadContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="main">
          <AuthContextProvider>
            <ThreadContextProvider>{children}</ThreadContextProvider>
          </AuthContextProvider>
        </main>
      </body>
    </html>
  );
}
